name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 리포지토리 코드 체크아웃
      - uses: actions/checkout@v3

      # 2. Java 설정 (Corretto 17 사용)
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      # 3. Gradle Wrapper 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 4. Gradle 캐시 설정
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # 5. Gradle 빌드 실행
      - name: Build with Gradle
        run: ./gradlew clean build
